# Generated by Django 6.0.4 on 2026-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aspect_ratio',
            field=models.CharField(choices=[('landscape', 'Landscape (1.91:1)'), ('square', 'Square (1:1)'), ('portrait', 'Portrait (4:5)')], default='landscape', max_length=20),
        ),
    ]
