# Generated by Django 6.0.4 on 2026-06-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bsnner',
            field=models.ImageField(default='default_banner.png', upload_to='banners'),
        ),
    ]
