# Generated by Django 6.0.4 on 2026-06-14 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_aspect_ratio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aspect_ratio',
            field=models.CharField(choices=[('landscape', 'Landscape (1.91:1)'), ('square', 'Square (1:1)'), ('portrait', 'Portrait (9:16)')], default='landscape', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_score', models.IntegerField(default=0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userpreferences')),
            ],
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='categories',
            field=models.ManyToManyField(blank=True, through='core.UserPreferredCategory', to='core.category'),
        ),
    ]
