# Generated by Django 6.0.4 on 2026-06-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bsnner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bsnner',
            new_name='banner',
        ),
    ]
