# Generated by Django 6.0.4 on 2026-06-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_aspect_ratio_userpreferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
