# Generated by Django 6.0.4 on 2026-07-07 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bsnner_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='last_decay',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpreferredcategory',
            name='interest_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferredcategory',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_categories', to='core.userpreferences'),
        ),
    ]
