# Generated by Django 6.0.4 on 2026-05-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
