# Generated by Django 6.0.4 on 2026-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
