# Generated by Django 6.0.4 on 2026-05-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
