# Generated by Django 6.0.4 on 2026-05-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_number_of_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_followers',
        ),
    ]
